src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventsRepository::class)
 */
class Events
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $hook;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_event;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=ImagesEvent::class, mappedBy="event", orphanRemoval=true, cascade={"persist"})
     */
    private $imagesEvents;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $annule;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $actif;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $event_blue_angels;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $epingle;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_lieu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=800, nullable=true)
     */
    private $lien_maps;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_modified_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_modified_by;

    public function __construct()
    {
        $this->imagesEvents = new ArrayCollection();
        $this->date_event = new \DateTime('now');
        $this->actif = true;
        $this->event_blue_angels = true;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getHook(): ?string
    {
        return $this->hook;
    }

    public function setHook(?string $hook): self
    {
        $this->hook = $hook;

        return $this;
    }

    public function getDateEvent(): ?\DateTimeInterface
    {
        return $this->date_event;
    }

    public function setDateEvent(\DateTimeInterface $date_event): self
    {
        $this->date_event = $date_event;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|ImagesEvent[]
     */
    public function getImagesEvents(): Collection
    {
        return $this->imagesEvents;
    }

    public function addImagesEvent(ImagesEvent $imagesEvent): self
    {
        if (!$this->imagesEvents->contains($imagesEvent)) {
            $this->imagesEvents[] = $imagesEvent;
            $imagesEvent->setEvent($this);
        }

        return $this;
    }

    public function removeImagesEvent(ImagesEvent $imagesEvent): self
    {
        if ($this->imagesEvents->removeElement($imagesEvent)) {
            // set the owning side to null (unless already changed)
            if ($imagesEvent->getEvent() === $this) {
                $imagesEvent->setEvent(null);
            }
        }

        return $this;
    }

    public function getAnnule(): ?bool
    {
        return $this->annule;
    }

    public function setAnnule(?bool $annule): self
    {
        $this->annule = $annule;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(?bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getEventBlueAngels(): ?bool
    {
        return $this->event_blue_angels;
    }

    public function setEventBlueAngels(?bool $event_blue_angels): self
    {
        $this->event_blue_angels = $event_blue_angels;

        return $this;
    }

    public function getEpingle(): ?bool
    {
        return $this->epingle;
    }

    public function setEpingle(?bool $epingle): self
    {
        $this->epingle = $epingle;

        return $this;
    }

    public function getNomLieu(): ?string
    {
        return $this->nom_lieu;
    }

    public function setNomLieu(?string $nom_lieu): self
    {
        $this->nom_lieu = $nom_lieu;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getLienMaps(): ?string
    {
        return $this->lien_maps;
    }

    public function setLienMaps(?string $lien_maps): self
    {
        $this->lien_maps = $lien_maps;

        return $this;
    }

    public function getLastModifiedAt(): ?\DateTimeInterface
    {
        return $this->last_modified_at;
    }

    public function setLastModifiedAt(?\DateTimeInterface $last_modified_at): self
    {
        $this->last_modified_at = $last_modified_at;

        return $this;
    }

    public function getLastModifiedBy(): ?string
    {
        return $this->last_modified_by;
    }

    public function setLastModifiedBy(?string $last_modified_by): self
    {
        $this->last_modified_by = $last_modified_by;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Events;
use PhpParser\Node\Expr\Cast\Bool_;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;


class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => 'Nom de l\'évènement',
            ])

            ->add('hook', TextType::class, [
                'required' => true,
                'label' => 'Phrase d\'accroche'
            ])

            // On ajoute le champ image dans le formulaire
            // Il n'est pas lié à la base de données (mapped à false)
            ->add('imageFile', FileType::class, [
                'required' => false,
                'label' => false,
                'multiple' => true,
                'mapped' => false,
                'constraints' => [
                    new All([
                        new Image([
                            // maxSize: Par fichier
                            'maxSize' => '8M',
                            'maxSizeMessage' => 'Trop gros: 8M maxi par fichier',
                            'mimeTypes' => [
                                'image/jpeg',
                                'image/png'
                            ],
                            'mimeTypesMessage' => 'Fichier non-valide: Uniquement jpeg et png'
                        ])
                    ])
                ]
            ])

            // CHAMPS SUPPLÉMENTAIRES POUR POUR CHAQUE IMAGE (CAPTION, AUTHOR)
            ->add('ImagesEvents', CollectionType::class, [
                'required' => false,
                'label' => false,
                'entry_type' => ImagesEventType::class,
                // 'allow_add' => true,
                // 'allow_delete' => true,

            ])

            ->add('date_event', DateTimeType::class, [
                'years' => range(date('Y') - 20, date('Y') + 20),
                'required' => true,
                'label' => 'Date de l\'évènement',
            ])

            ->add('nom_lieu', TextType::class, [
                'required' => false,
                'label' => 'Nom du lieu'
            ])

            ->add('adresse', TextType::class, [
                'required' => false,
                'label' => 'Adresse'
            ])

            ->add('code_postal', TextType::class, [
                'required' => false,
                'label' => 'Code postal'
            ])

            ->add('ville', TextType::class, [
                'required' => false,
                'label' => 'Ville'
            ])

            ->add('description', TextareaType::class, [
                'label' => 'Description de l\'évènement',
            ])

            ->add('lien_maps', TextType::class, [
                'required' => false,
                'label' => 'Lien maps'
            ])

            ->add('annule', CheckboxType::class, [
                'required' => false,
                'label' => 'Annulé',
            ])

            ->add('epingle', CheckboxType::class, [
                'required' => false,
                'label' => 'Épinglé'
            ])

            ->add('actif', CheckboxType::class, [
                'required' => false,
                'label' => 'Actif',
            ])

            ->add('event_blue_angels', CheckboxType::class, [
                'required' => false,
                'label' => 'Organisé par les Blue Angels',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Events::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Events;
use App\Repository\ImagesEventRepository;
use App\Service\TodayGenerator;

class EventController extends AbstractController
{
    /**
     * @Route("/event/{id}", name="event_")
     */
    public function eventLoad($id, TodayGenerator $todayGenerator, ImagesEventRepository $imagesEventRepository): Response
    {
        // On récupère la date du jour, que l'on peut changer dans la classe
        $today = $todayGenerator->generateAToday();
        $repo = $this->getDoctrine()->getRepository(Events::class);

        // On récupère l'event par son id, et seulement s'il est actif
        $event = $repo->findOneBy(
            [
                'id' => $id,
                'actif' => true,
            ]

        );

        // On determine si l'event est futur ou passé
        if ($event->getDateEvent()->format('Y-m-d') >= $today->format('Y-m-d')) {
            $epoque = "futur";
        }
        else
        $epoque = "passe";

        if (empty($event)) {
            // Erreur 404
            throw $this->createNotFoundException('L\'évènement n\'est pas actif');
        }

        $images = $imagesEventRepository->findBy(['event' => $event]);
        return $this->render('event/fullPageEvent.html.twig', [
            'event' => $event,
            'images' => $images,
            'today' => $today,
            'epoque' => $epoque,
        ]);
    }
}

templates/events/_eventsBase.html.twig
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('css/cardApercuArticle.css') }}">
<link rel="stylesheet" href="{{ asset('css/boutonsEtInputs.css') }}">
{% endblock %}

{#
On affiche les aperçus des elements, s'il y en a, dans des cards.
Chaque card est cliquable, et renvoi vers la fullPage de l'element.
#}


{% if events is not empty %}
<div class="bloc-cards">
	{% for event in events %}
	<a class="card-article" href="{{ path('event_', {id: event.id}) }}"
		title="{{ event.getNom ~ ' | ' ~ event.getHook ~ ' | ' ~ event.getDateEvent | format_datetime(pattern=" EEEE dd
		LLLL yyyy HH:mm", locale="fr" ) | capitalize ~ ' | ' ~ event.getVille }}">


		{% if event.eventBlueAngels %}
		<div class="etiquette-event-blue-angels">
			<img src="{{ asset('images/favicon.png') }}" alt="Icone des Blue Angels">
		</div>
		{% endif %}
		{% if epoque == 'futur' %}
		{# Info jours dans une petite étiquette incrustée en haut à gauche de la carte #}
		{# Petite étiquette "épinglé" à gauche de l'autre étiquette du jour #}
		{% if event.epingle %}
		<div class="etiquette-epingle">
			{# <img src="{{ asset('images/punaise3d.svg') }}" alt="punaise3d"> #}
			<i class="fas fa-thumbtack yellow"></i>&nbsp;
			<span>Évènement épinglé</span>
		</div>
		{% endif %}

		{% for j in 0..999 %}
		{% if j == 0 %}
		{# Si l'event est aujourd'hui #}
		{% if event.getDateEvent()|date("Y-m-d") == today|date("Y-m-d")|date("Y-m-d") %}
		<div class="etiquette-decompte-jours-event">
			<div class="contenu-etiquette-decompte-jours-event">
				<div class="bloc-haut green">
					Aujourd'hui
				</div>
				{# Si l'heure de l'event est <= à l'heure actuelle #} {% if event.getDateEvent | date("H:i") <=today |
					date("H:i") %} <div class="bloc-milieu aujourdhui red blinking">{{ event.getDateEvent | date("H:i") }}
			</div>
			{% else %}
			<div class="bloc-milieu aujourdhui green">{{ event.getDateEvent | date("H:i") }}</div>
			{% endif %}
		</div>
</div>
{% endif %}
{% elseif j == 1 %}
{# Si l'event est demain #}
{% if event.getDateEvent()|date("Y-m-d") == today|date_modify("+"~ j ~" day")|date("Y-m-d") %}
<div class="etiquette-decompte-jours-event">
	<div class="contenu-etiquette-decompte-jours-event blue">
		<div class="bloc-milieu">D</div>
		<div class="bloc-bas">Demain</div>
	</div>
</div>
{% endif %}
{% else %}
{# Si l'event est plus tard #}
{% if event.getDateEvent()|date("Y-m-d") == today|date_modify("+"~ j ~" day")|date("Y-m-d") %}
<div class="etiquette-decompte-jours-event">
	<div class="contenu-etiquette-decompte-jours-event">
		<div class="bloc-haut">Dans</div>
		<div class="bloc-milieu">{{ j }}</div>
		<div class="bloc-bas">Jours</div>
	</div>
</div>
{% endif %}
{% endif %}
{% endfor %}
{% endif %}

{% if event.getImagesEvents[0].getNom() is defined %}
<div class="image">
	<img src="{{ asset('uploads/imagesEvents/' ~ 'min_' ~ event.getImagesEvents[0].Nom) }}" alt="">
</div>
{% endif %}
<div class="bloc-text">
	{% if event.getAnnule %}
	<div class="tampon-oblique-red">Évènement annulé</div>
	{% endif %}
	<h3 class="titre">{{ event.getNom() }}</h3>
	<div class="hook">{{ event.getHook() }}</div>
	{# Bouton en forme de flèche comme pour les articles #}
	{# {% if event.getImagesEvents[0].getNom() is defined %} #}
	<div class="backgroundRond centerCard">
		<i class="fas fa-arrow-right fa-lg flecheDroiteCard"></i>
	</div>
	{# {% else %} #}
	{# <div class="backgroundRondSansImage centerCard">
		<i class="fas fa-arrow-right fa-lg flecheDroiteCard"></i>
	</div> #}
	{# {% endif %} #}
	<div class="info-epoque-event">
		{% if epoque == 'passé' %}
		<span class="info-jour">Terminé</span>
		{% endif %}


	</div>

	<div class="infos infos-event">
		<div class="articles-date">
			<i class="fas fa-calendar-alt"></i>
			{{ event.getDateEvent()|date("d-m-Y") }}
		</div>
		{% if event.ImagesEvents | length > 1 %}
		<div class="articles-nbr-images">
			<i class="fas fa-image"></i>
			{{ event.ImagesEvents | length }}
		</div>
		{% endif %}
	</div>
</div>
</a>
{% endfor %}
</div>
{% endif %}

templates/events/completedEvents.html.twig
{% extends 'components/base.html.twig' %}
{% block stylesheets %}{% endblock %}

{% block title %}
	{{ SiteName }}: Évènements passés
{% endblock %}

{% block body %}
	<div class="wrapper">
		{% set countPasse = countTotalCompletedEvents[0][1] %}
		{% set countAVenir = countTotalEventsToCome[0][1] %}

		<h1>
			Évènements passés
		</h1>
		{% if countAVenir > 0 %}
			<h4>Voir aussi
				<a class="bouton bt2" href="{{ path('a_venir') }}" title="{{ countAVenir }} évènement(s) à venir">
					Évènements à venir ({{ countAVenir }})
				</a>
			</h4>
		{% endif %}
		<section class="events">
			{{ include ('events/_eventsBase.html.twig') }}
		</section>
	</div>
{% endblock %}

templates/events/eventsToCome.html.twig
{% extends 'components/base.html.twig' %}
{% block stylesheets %}{% endblock %}

{% block title %}
	{{ SiteName }}: Évènements à venir
{% endblock %}

{% block body %}
	<div class="wrapper">
		{% set countPasse = countTotalCompletedEvents[0][1] %}
		{% set countAVenir = countTotalEventsToCome[0][1] %}

		{% if countAVenir > 0 %}
			{% if countAVenir == 1 %}
				<h1>Évènement à venir: 1</h1>
			{% else %}
				<h1>Évènements à venir:
					{{ countAVenir }}
				</h1>
			{% endif %}
		{% else %}
			<h1>Aucun évènement à venir</h1>
			{% if countPasse > 0 %}
				<h4>Voir aussi
					<a class="bouton bt2" href="{{ path('completed_events') }}">
						Évènements passés
					</a>
				</h4>
			{% endif %}


		{% endif %}
		<section class="events">
			{{ include ('events/_eventsBase.html.twig') }}
		</section>
	</div>
{% endblock %}